version: '3'

services:
  database:
    image: mysql
    restart: always
    container_name: 'mysql'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
